/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBarAppBar: typeof import('./../src/components/AppBar/AppBar.vue')['default']
    BoxL: typeof import('./../src/components/LayoutCompositions/BoxL.vue')['default']
    ClusterL: typeof import('./../src/components/LayoutCompositions/ClusterL.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    NavigationMobileNavigationMobile: typeof import('./../src/components/NavigationMobile/NavigationMobile.vue')['default']
    PageBlockPageBlock: typeof import('./../src/components/PageBlock/PageBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackL: typeof import('./../src/components/LayoutCompositions/StackL.vue')['default']
    TextL: typeof import('./../src/components/LayoutCompositions/TextL.vue')['default']
  }
}
